apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: itinventory-devops
  labels:
    app.kubernetes.io/name: itinventory-backend
    app.kubernetes.io/part-of: itinventory
    app.kubernetes.io/version: "2026-01-14-01"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: itinventory-backend
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081