apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: itinventory-devops
data:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/itinventory"
  SERVER_PORT: "8081"