{
 "title": "ITInventory Backend Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Conexões Ociosas do HikariCP",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "hikaricp_connections_idle", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU da Aplicação",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Conexões Ativas do HikariCP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time(hikaricp_connections_active[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições HTTP por Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (uri) (http_server_requests_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads da JVM",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memória JVM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "sum(jvm_memory_used_bytes)", "legendFormat": "__auto" }
   ]
  }
 ]
}